services:
  # ======================
  # MySQL Database
  # ======================
  mysql:
    container_name: genai_mysql
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: genai_med
      MYSQL_USER: genai
      MYSQL_PASSWORD: genai
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-prootpass"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - genai_network

  # ======================
  # phpMyAdmin
  # ======================

  phpmyadmin:
    container_name: genai_phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    depends_on:
      - mysql
    environment:
      PMA_HOST: genai_mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: rootpass
    ports:
      - "8081:80"
    networks:
      - genai_network

  # ======================
  # Redis
  # ======================
  redis:
    container_name: genai_redis
    image: redis
    ports:
      - "6379:6379"
    networks:
      - genai_network
    restart: always

  # ======================
  # Qdrant
  # ======================
  qdrant:
    container_name: genai_qdrant
    image: qdrant/qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    networks:
      - genai_network
    restart: always

  # ======================
  # Backend (FastAPI)
  # ======================
  backend:
    container_name: genai_backend
    build:
      context: ../backend
      dockerfile: Dockerfile
    command: >
      sh -c "pip install cryptography && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - "8000:8000"
    volumes:
      - ../backend:/app
    environment:
      DATABASE_URL: mysql+pymysql://genai:genai@mysql:3306/genai_med
      REDIS_URL: redis://redis:6379
      QDRANT_URL: http://qdrant:6333
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
      qdrant:
        condition: service_started
    networks:
      - genai_network
    restart: always

  # ======================
  # Celery Worker
  # ======================
  # celery:
  #   container_name: genai_celery
  #   build:
  #     context: ../backend
  #     dockerfile: Dockerfile
  #   command: >
  #     sh -c "pip install cryptography && celery -A app.celery_app.celery_app worker --loglevel=info"
  #   volumes:
  #     - ../backend:/app
  #   environment:
  #     DATABASE_URL: mysql+pymysql://genai:genai@mysql:3306/genai_med
  #     REDIS_URL: redis://redis:6379
  #     QDRANT_URL: http://qdrant:6333
  #   depends_on:
  #     backend:
  #       condition: service_started
  #     redis:
  #       condition: service_started
  #     mysql:
  #       condition: service_healthy
  #   networks:
  #     - genai_network
  #   restart: always

  # ======================
  # Frontend (React + Vite)
  # ======================
  frontend:
      build:
        context: ../frontend
        dockerfile: Dockerfile
      container_name: genai-frontend
      ports:
        - "5173:5173"
      volumes:
        - ../frontend/vite-react/src:/app/src
        - ../frontend/vite-react/index.html:/app/index.html
      working_dir: /app
      command: npm run dev


# ======================
# Volumes
# ======================
volumes:
  mysql_data:
  redis_data:
  qdrant_data:
  backend_data:
  frontend_node_modules:
  celery_data:

# ======================
# Shared Network
# ======================
networks:
  genai_network:
    driver: bridge
