services:
  backend:
    build: ../backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ../backend:/app
      - ../data/uploads:/app/data/uploads
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=genai
      - MYSQL_PASSWORD=genai
      - MYSQL_DB=genai_med
      - QDRANT_URL=http://qdrant:6333
      - REDIS_HOST=redis
      - REDIS_PORT=6379


  celery:
    build: ../backend
    command: celery -A worker.celery_app worker --loglevel=info
    volumes:
      - ../backend:/app
    depends_on:
      - redis
      - mysql
      - qdrant
    environment:
      - REDIS_HOST=redis
      - MYSQL_HOST=mysql
      - QDRANT_URL=http://qdrant:6333

  frontend:
    working_dir: /app
    build: ../frontend
    ports:
      - "3000:3000"
    volumes:
      - ../frontend:/app
    command: npm run dev
    depends_on:
      - backend
